name: stx_tree_view
description: A Flutter package for a fully customisable base tree view. Using this package you can build nested tree view with the possibility of making each child widget a parent.
version: 0.0.3

homepage: https://github.com/VolodymyrSydorko/stx_tree_view
repository: https://github.com/VolodymyrSydorko/stx_tree_view
documentation: https://github.com/VolodymyrSydorko/stx_tree_view

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
